/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/business_unit": {
    /** List all business units */
    get: {
      parameters: {
        query?: {
          /** @description Offset of the business units to be listed. */
          offset?: number;
          /** @description Limit of the business units to be listed. */
          limit?: number;
        };
      };
      responses: {
        /** @description Business units retrieved successfully */
        200: {
          content: {
            "application/json": {
              /**
               * Format: int32
               * @description Total number of business units.
               */
              total?: number;
              /** @description Records of business units. */
              records?: components["schemas"]["ListBusinessUnitsRecord"][];
            };
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Create a new business unit */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateBusinessUnitRequest"];
        };
      };
      responses: {
        /** @description Business unit created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["BusinessUnit"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/business_unit/{id}": {
    /** Get a specific business unit */
    get: {
      parameters: {
        path: {
          /** @description The ID of the business unit to retrieve. */
          id: string;
        };
      };
      responses: {
        /** @description Business unit retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ListBusinessUnitsRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Business unit not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Update a specific business unit */
    post: {
      parameters: {
        path: {
          /** @description The ID of the business unit to update. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description User who makes the request. */
            requester: string;
            /** @description Unique DID of a BusinessUnit. */
            id: string;
            /** @description Name of the BusinessUnit. */
            name: string;
            /** @description List of addresses associated with the BusinessUnit. */
            addresses?: string[];
            /** @description Country Code of the BusinessUnit. (Eg: US, SG, CA) */
            country?: string;
            /** @description List of emails associated with the BusinessUnit. */
            emails?: string[];
            /** @description List of phone numbers associated with the BusinessUnit. */
            phone_numbers?: string[];
          };
        };
      };
      responses: {
        /** @description Business unit updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessUnit"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Business unit not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/business_unit/{id}/status": {
    /** Set the status of a specific business unit */
    post: {
      parameters: {
        path: {
          /** @description The ID of the business unit to update. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description User who makes the request. */
            requester: string;
            /** @description Status of the application. */
            status: components["schemas"]["BusinessUnitStatus"];
          };
        };
      };
      responses: {
        /** @description Business unit status updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessUnit"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Business unit not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/business_unit/{id}/authentication": {
    /** List all authentications for a business unit */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description List of authentications retrieved successfully */
        200: {
          content: {
            "application/json": {
              /**
               * Format: int32
               * @description Total number of authentications
               */
              total?: number;
              /** @description Records of authentications */
              records?: components["schemas"]["BusinessUnitAuthentication"][];
            };
          };
        };
        /** @description Bad request, invalid parameters or business unit ID */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Create a new authentication for a business unit */
    post: {
      parameters: {
        path: {
          /** @description The ID of the business unit */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description User who makes the request */
            requester: string;
            /** @description Option of the private key. */
            private_key_option: components["schemas"]["PrivateKeyOption"];
            /**
             * Format: int64
             * @description How long (in second) the authentication/certificate will be valid.
             */
            expired_after: number;
          };
        };
      };
      responses: {
        /** @description Authentication created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["BusinessUnitAuthentication"];
          };
        };
        /** @description Bad request, invalid parameters or business unit ID */
        400: {
          content: never;
        };
        /** @description Business unit not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/business_unit/{id}/authentication/{authentication_id}": {
    /** Get a specific authentication for a business unit */
    get: {
      parameters: {
        path: {
          /** @description The ID of the business unit */
          id: string;
          /** @description The ID of the authentication */
          authentication_id: string;
        };
      };
      responses: {
        /** @description Authentication retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessUnitAuthentication"];
          };
        };
        /** @description Bad request, invalid parameters or business unit ID */
        400: {
          content: never;
        };
        /** @description Authentication not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Revoke a specific authentication for a business unit */
    delete: {
      parameters: {
        query?: {
          /** @description User who makes the request */
          requester?: string;
        };
        path: {
          /** @description The ID of the business unit */
          id: string;
          /** @description The ID of the authentication */
          authentication_id: string;
        };
      };
      responses: {
        /** @description Authentication revoked successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessUnitAuthentication"];
          };
        };
        /** @description Bad request, invalid parameters or business unit ID */
        400: {
          content: never;
        };
        /** @description Authentication not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl": {
    /** List all eB/L */
    get: {
      parameters: {
        query?: {
          /** @description Number of items to skip before returning the results */
          offset?: number;
          /** @description Maximum number of items to return */
          limit?: number;
          /** @description Status of the eB/L to be listed */
          status?: "action_needed" | "upcoming" | "sent" | "archive";
          /** @description whether to include the report */
          report?: boolean;
        };
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
      };
      responses: {
        /** @description eB/L retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ListBillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Issue or draft a new eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}": {
    /** Get a specific eB/L */
    get: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to retrieve. */
          id: string;
        };
      };
      responses: {
        /** @description eB/L retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/document": {
    /** Download the uploaded eB/L document */
    get: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to retrieve */
          id: string;
        };
      };
      responses: {
        /** @description eB/L file retrieved successfully */
        200: {
          content: {
            "application/octet-stream": string;
            "application/pdf": string;
            "image/jpeg": string;
            "image/png": string;
            "image/tiff": string;
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found or eB/L has no document */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/update": {
    /** Update the draft eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/transfer": {
    /** Transfer the eB/L to next owner */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to transfer */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TransferBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L transferred successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/return": {
    /** Return the eB/L to last owner */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to return */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReturnBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L returned successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/surrender": {
    /** Transfer the eB/L to the release agent */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to surrender */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SurrenderBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L surrendered successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/accomplish": {
    /** Accomplish the eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to accomplish */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AccomplishBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L accomplished successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/print_to_paper": {
    /** Print the eB/L to paper */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to print to paper */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PrintToPaperBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L printed to paper successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/amendment_request": {
    /** Request amendment for the eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to request amendment */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AmendmentRequestBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L requested amendment successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/amend": {
    /** Amend the eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to amend */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AmendBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L amended successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/ebl/{id}/delete": {
    /** Delete the draft eB/L */
    post: {
      parameters: {
        header?: {
          "X-Business-Unit-ID"?: components["parameters"]["BURequestHeader"];
        };
        path: {
          /** @description The ID of the eB/L to amend */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DeleteBillOfLadingRequest"];
        };
      };
      responses: {
        /** @description eB/L amended successfully */
        200: {
          content: {
            "application/json": components["schemas"]["BillOfLadingRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description eB/L not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/webhook": {
    /** List all webhook */
    get: {
      parameters: {
        query?: {
          /** @description Number of items to skip before returning the results */
          offset?: number;
          /** @description Maximum number of items to return */
          limit?: number;
        };
      };
      responses: {
        /** @description webhook retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ListWebhookRecord"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Create a new webhook */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateWebhookRequest"];
        };
      };
      responses: {
        /** @description webhook created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["Webhook"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/webhook/{id}": {
    /** Get a specific webhook */
    get: {
      parameters: {
        path: {
          /** @description The ID of the webhook to retrieve */
          id: string;
        };
      };
      responses: {
        /** @description webhook retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["Webhook"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description webhook not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Update a specific webhook */
    post: {
      parameters: {
        path: {
          /** @description The ID of the webhook to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateWebhookRequest"];
        };
      };
      responses: {
        /** @description webhook updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["Webhook"];
          };
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description webhook not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Delete a specific webhook */
    delete: {
      parameters: {
        path: {
          /** @description The ID of the webhook to delete */
          id: string;
        };
      };
      responses: {
        /** @description webhook deleted successfully */
        200: {
          content: never;
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description webhook not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description Type of the private key.
     * @enum {string}
     */
    PrivateKeyType: "RSA" | "ECDSA";
    /**
     * @description Curve type of the private key.
     * @enum {string}
     */
    ECDSACurveType: "P-256" | "P-384" | "P-521";
    PrivateKeyOption: {
      /** @description Type of the private key. */
      key_type?: components["schemas"]["PrivateKeyType"];
      /**
       * Format: int32
       * @description Bit length of the private key. Only used when KeyType is RSA.
       */
      bit_length?: number;
      /** @description Curve type of the private key. Only used when KeyType is ECDSA. */
      curve_type?: components["schemas"]["ECDSACurveType"];
    };
    /** @enum {string} */
    BusinessUnitStatus: "active" | "inactive";
    /**
     * @description Status of the authentication.
     * @enum {string}
     */
    BusinessUnitAuthenticationStatus: "active" | "revoked";
    BusinessUnit: {
      /** @description Unique DID of a BusinessUnit. */
      id?: string;
      /**
       * Format: int64
       * @description Version of the BusinessUnit.
       */
      version?: number;
      /** @description The ID of the application this BusinessUnit belongs to. */
      application_id?: string;
      status?: components["schemas"]["BusinessUnitStatus"];
      /** @description Name of the BusinessUnit. */
      name?: string;
      /** @description List of addresses associated with the BusinessUnit. */
      addresses?: string[];
      /** @description Country Code of the BusinessUnit. (Eg: US, SG, CA) */
      country?: string;
      /** @description List of emails associated with the BusinessUnit. */
      emails?: string[];
      /** @description List of phone numbers associated with the BusinessUnit. */
      phone_numbers?: string[];
      /**
       * Format: int64
       * @description Unix Time (in second) when the BusinessUnit was created.
       */
      created_at?: number;
      /** @description User who created the BusinessUnit. */
      created_by?: string;
      /**
       * Format: int64
       * @description Unix Time (in second) when the BusinessUnit was last updated.
       */
      updated_at?: number;
      /** @description User who last updated the BusinessUnit. */
      updated_by?: string;
    };
    BusinessUnitAuthentication: {
      /** @description Unique ID of the authentication. */
      id?: string;
      /**
       * Format: int64
       * @description Version of the authentication.
       */
      version?: number;
      /** @description Unique DID of a BusinessUnit. */
      business_unit?: string;
      status?: components["schemas"]["BusinessUnitAuthenticationStatus"];
      /**
       * Format: int64
       * @description Unix Time (in second) when the authentication was created.
       */
      created_at?: number;
      /** @description User who created the authentication. */
      created_by?: string;
      /**
       * Format: int64
       * @description Unix Time (in second) when the authentication was revoked.
       */
      revoked_at?: number;
      /** @description User who revoked the authentication. */
      revoked_by?: string;
      /** @description PEM encoded private key. */
      private_key?: string;
      /** @description PEM encoded certificate. */
      certificate?: string;
      /** @description PEM encoded intermediate certificates. */
      intermediate_certs?: string[];
    };
    ListBusinessUnitsRecord: {
      business_unit?: components["schemas"]["BusinessUnit"];
      /** @description The authentications of the business unit. */
      authentications?: components["schemas"]["BusinessUnitAuthentication"][];
    };
    CreateBusinessUnitRequest: {
      /** @description User who makes the request. */
      requester: string;
      /** @description Name of the BusinessUnit. */
      name: string;
      /** @description List of addresses associated with the BusinessUnit. */
      addresses?: string[];
      /** @description Country Code of the BusinessUnit. (Eg: US, SG, CA) */
      country?: string;
      /** @description List of emails associated with the BusinessUnit. */
      emails?: string[];
      /** @description List of phone numbers associated with the BusinessUnit. */
      phone_numbers?: string[];
      status: components["schemas"]["BusinessUnitStatus"];
    };
    /**
     * @description B/L Document Type
     * @enum {string}
     */
    BillOfLadingDocumentType: "MasterBillOfLading" | "HouseBillOfLading";
    /**
     * @description B/L Type
     * @enum {string}
     */
    BillOfLadingType: "NonNegotiable" | "Negotiable";
    /**
     * @description action to perform on the eB/L
     * @enum {string}
     */
    BillOfLadingAction: "UPDATE_DRAFT" | "AMEND" | "REQUEST_AMEND" | "PRINT" | "TRANSFER" | "RETURN" | "SURRENDER" | "ACCOMPLISH" | "DELETE";
    /**
     * @description Document status
     * @enum {string}
     */
    DocumentStatus: "DRFT" | "ISSU";
    /** @description Refers to a company or a legal entity */
    Party: {
      /** @description Name of the party */
      partyName?: string;
      identifyingCodes?: components["schemas"]["IdentifyingCode"][];
    };
    /** Identifying Code */
    IdentifyingCode: {
      partyCode: components["schemas"]["partyCode"];
    };
    /** @description Code to identify the party as provided by the agency */
    partyCode: string;
    /** @description Party involved in the transport document */
    DocumentParty: {
      party?: components["schemas"]["Party"];
      /**
       * @description Role of the party
       * @enum {string}
       */
      partyFunction?: "DDR" | "OS" | "CN" | "DDS";
    };
    /** @description Enrichment to the original booking shard by the shipper to the carrier */
    ShippingInstruction: {
      /** @description B/L Number */
      shippingInstructionReference?: string;
      documentStatus?: components["schemas"]["DocumentStatus"];
      /** @description Indicate if the eB/L is negotiable */
      isToOrder?: boolean;
      /** @description Parties involved in the eB/L */
      documentParties?: components["schemas"]["DocumentParty"][];
    };
    Location: {
      /** @description Name of the location */
      locationName?: string;
      /** @description UN location code */
      UNLocationCode?: string;
    };
    /** @description Maps the relationship between shipment and location */
    ShipmentLocation: {
      location?: components["schemas"]["Location"];
      /** @enum {string} */
      shipmentLocationTypeCode?: "POL" | "POD";
      /**
       * Format: date-time
       * @description When the event happened
       */
      eventDateTime?: string;
    };
    Transport: {
      /** @enum {string} */
      transportPlanStage?: "PRC" | "MNC" | "ONC";
      /**
       * Format: date-time
       * @description Estimated time of arrival
       */
      plannedArrivalDate?: string;
    };
    /** @description Document that governs the terms of carriage between shipper and carrier for maritime transportation */
    TransportDocument: {
      shippingInstruction?: components["schemas"]["ShippingInstruction"];
      /**
       * Format: date-time
       * @description When the document was created
       */
      transportDocumentCreatedDateTime?: string;
      /**
       * Format: date-time
       * @description When the document was updated
       */
      transportDocumentUpdatedDateTime?: string;
      shipmentLocations?: components["schemas"]["ShipmentLocation"][];
      transports?: components["schemas"]["Transport"][];
    };
    /** @description Metadata of the uploaded document */
    FileInfo: {
      /** @description File name of the uploaded document */
      name?: string;
      /** @description MIME type of the uploaded document */
      type?: string;
    };
    /** @description Metadata of the uploaded document */
    File: {
      /** @description File name of the uploaded document */
      name?: string;
      /** @description MIME type of the uploaded document */
      type?: string;
      /**
       * Format: byte
       * @description base64-encoded content of the document
       */
      content?: string;
    };
    /** @description Event of issuing the eB/L */
    BillOfLading: {
      bill_of_lading?: components["schemas"]["TransportDocument"];
      file?: components["schemas"]["FileInfo"];
      doc_type?: components["schemas"]["BillOfLadingDocumentType"];
      /** @description DID of the next owner */
      transfer_to?: string;
      /** @description DID of the issuing agent */
      created_by?: string;
      /**
       * Format: date-time
       * @description When the eB/L was created
       */
      created_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of transferring the eB/L */
    Transfer: {
      /** @description DID of the business unit who makes the transfer */
      transfer_by?: string;
      /** @description DID of the business unit who receives the transfer */
      transfer_to?: string;
      /**
       * Format: date-time
       * @description When the eB/L was transferred
       */
      transfer_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of returning the eB/L */
    Return: {
      /** @description DID of the business unit who makes the return */
      return_by?: string;
      /** @description DID of the business unit who receives the return */
      return_to?: string;
      /**
       * Format: date-time
       * @description When the eB/L was returned
       */
      return_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of surrendering the eB/L */
    Surrender: {
      /** @description DID of the business unit who makes the surrender */
      surrender_by?: string;
      /** @description DID of the business unit who receives the surrender */
      surrender_to?: string;
      /**
       * Format: date-time
       * @description When the eB/L was surrendered
       */
      surrender_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of requesting amendment for the eB/L */
    AmendmentRequest: {
      /** @description DID of the business unit who makes the request */
      request_by?: string;
      /** @description DID of the business unit who receives the request */
      request_to?: string;
      /**
       * Format: date-time
       * @description When the eB/L was requested amendment
       */
      request_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of printing the eB/L to paper */
    PrintToPaper: {
      /** @description DID of the business unit who makes the print to paper */
      print_by?: string;
      /**
       * Format: date-time
       * @description When the eB/L was printed to paper
       */
      print_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of accomplishing the eB/L */
    Accomplish: {
      /** @description DID of the business unit who makes the accomplish */
      accomplish_by?: string;
      /**
       * Format: date-time
       * @description When the eB/L was accomplished
       */
      accomplish_at?: string;
      /** @description Optional note from the requester */
      note?: string;
      /** @description All fully customized data. */
      meta_data?: string;
    };
    /** @description Event of the eB/L */
    BillOfLadingEvent: {
      bill_of_lading?: components["schemas"]["BillOfLading"];
      transfer?: components["schemas"]["Transfer"];
      return?: components["schemas"]["Return"];
      surrender?: components["schemas"]["Surrender"];
      amendment_request?: components["schemas"]["AmendmentRequest"];
      print_to_paper?: components["schemas"]["PrintToPaper"];
      accomplish?: components["schemas"]["Accomplish"];
    };
    /** @description Detail information of the eB/L */
    BillOfLadingPack: {
      /** @description Unique ID of a eB/L */
      id?: string;
      /**
       * Format: int64
       * @description Version of the eB/L
       */
      version?: number;
      /** @description SHA512 hash of the previous version of the eB/L */
      parent_hash?: string;
      /** @description DID of the current owner */
      current_owner?: string;
      /** @description eB/L history event list */
      events?: components["schemas"]["BillOfLadingEvent"][];
    };
    BillOfLadingRecord: {
      allowed_actions?: components["schemas"]["BillOfLadingAction"][];
      bl?: components["schemas"]["BillOfLadingPack"];
    };
    ListBillOfLadingReport: {
      /**
       * Format: int32
       * @description Number of eB/Ls that need action
       */
      action_needed?: number;
      /**
       * Format: int32
       * @description Number of upcoming eB/Ls
       */
      upcoming?: number;
      /**
       * Format: int32
       * @description Number of sent eB/Ls
       */
      sent?: number;
      /**
       * Format: int32
       * @description Number of archived eB/Ls
       */
      archive?: number;
    };
    ListBillOfLadingRecord: {
      /**
       * Format: int32
       * @description Total number of the eB/L
       */
      total?: number;
      records?: components["schemas"]["BillOfLadingRecord"][];
      report?: components["schemas"]["ListBillOfLadingReport"];
    };
    /**
     * @description event to trigger the webhook
     * @enum {string}
     */
    WebhookEventType: "bl.issued" | "bl.transferred" | "bl.returned" | "bl.amendment_requested" | "bl.amended" | "bl.surrendered" | "bl.accomplished" | "bl.printed_to_paper" | "bu.created" | "bu.updated" | "auth.created" | "auth.revoked";
    Webhook: {
      /** @description Unique ID of a webhook */
      id?: string;
      /**
       * Format: int64
       * @description Version of the webhook
       */
      version?: number;
      /** @description The URL that should have the event issued to it */
      url?: string;
      /**
       * Format: int64
       * @description Unix Time (in second) when the webhook was created
       */
      created_at?: number;
      /** @description User who created the webhook */
      created_by?: string;
      /**
       * Format: int64
       * @description Unix Time (in second) when the webhook was last updated
       */
      updated_at?: number;
      /** @description User who last updated the webhook */
      updated_by?: string;
      events?: components["schemas"]["WebhookEventType"][];
      /** @description secret key used to generate the signature */
      secret?: string;
    };
    /** @description Webhook event sent to the given URL */
    WebhookEvent: {
      /** @description Unique ID of the object that is the subject of the event trigger */
      id?: string;
      type?: components["schemas"]["WebhookEventType"];
      /**
       * Format: int64
       * @description Unix Time (in second) when the event was created
       */
      created_at?: number;
    };
    ListWebhookRecord: {
      /**
       * Format: int32
       * @description Total number of the webhook
       */
      total?: number;
      records?: components["schemas"]["Webhook"][];
    };
    BaseRequest: {
      /** @description All fully customized data. */
      meta_data?: string;
    };
    UpdateBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description The file associated with the request */
      file: components["schemas"]["File"];
      /** @description The bill of lading number */
      bl_number: string;
      /** @description The type of the bill of lading document */
      bl_doc_type?: components["schemas"]["BillOfLadingDocumentType"];
      /** @description Indicates if the request is to order. */
      to_order?: boolean;
      /** @description The port of loading. It's optional when draft is true. */
      pol: components["schemas"]["Location"];
      /** @description The port of discharge. It's optional when draft is true. */
      pod: components["schemas"]["Location"];
      /**
       * Format: date-time
       * @description The estimated time of arrival
       */
      eta?: string;
      /** @description The shipper of the eB/L. It's a DID of the business unit. It's optional when draft is true. */
      shipper: string;
      /** @description The consignee of the eB/L. It's a DID of the business unit. It's optional when draft is true. */
      consignee: string;
      /** @description The release agent of the eB/L. It's a DID of the business unit. It's optional when draft is true. */
      release_agent: string;
      /** @description Any additional notes */
      note?: string;
      /** @description Indicates if the eB/L is a draft */
      draft: boolean;
    };
    TransferBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    ReturnBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    SurrenderBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    AccomplishBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    PrintToPaperBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id?: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    AmendmentRequestBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note: string;
    };
    AmendBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description The file associated with the request */
      file: components["schemas"]["File"];
      /** @description B/L number */
      number: string;
      document_type: components["schemas"]["BillOfLadingDocumentType"];
      bl_type: components["schemas"]["BillOfLadingType"];
      /** @description Port of loading */
      pol: string;
      /** @description Port of discharge */
      pod: string;
      /**
       * Format: date-time
       * @description Estimate time of arrival
       */
      eta?: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    DeleteBillOfLadingRequest: components["schemas"]["BaseRequest"] & {
      /** @description The ID for authentication. The eB/L will be signed with the authentication. */
      authentication_id: string;
      /** @description Optional note from the requester */
      note?: string;
    };
    UpdateWebhookRequest: {
      /** @description User who makes the request */
      requester: string;
      /** @description The URL that should have WebhookEvent issued to it */
      url: string;
      events: components["schemas"]["WebhookEventType"][];
      /** @description Secret key used to create a hash signature that's sent to the url with each payload */
      secret: string;
    };
  };
  responses: never;
  parameters: {
    /** @description DID of the business unit who makes the request */
    BURequestHeader?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
