/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "bluex_errors";

export interface Error {
  code: Error_ErrorCode;
  message: string;
}

export enum Error_ErrorCode {
  UNKNOWN = 0,
  /** PREBOOKING_INVALID_PARAMETER - prebooking service */
  PREBOOKING_INVALID_PARAMETER = 1001000400,
  PREBOOKING_QUOTE_NOT_FOUND = 1001000404,
  /** COORDINATOR_INVALID_BOOKING_ID - booking service */
  COORDINATOR_INVALID_BOOKING_ID = 1002001001,
  COORDINATOR_VALIDATION_FAILED = 1002001002,
  COORDINATOR_INVALID_PARAMETER = 1002001003,
  COORDINATOR_BOOKING_NOT_FOUND = 1002001004,
  COORDINATOR_BOOKING_QUOTE_EXPIRED = 1002001005,
  /** COORDINATOR_INVALID_INVENTORY - booking service inventory */
  COORDINATOR_INVALID_INVENTORY = 1002002001,
  COORDINATOR_INSUFFICIENT_INVENTORY = 1002002002,
  COORDINATOR_OVER_BOOKING_CLOSING_TIME = 1002002003,
  COORDINATOR_DUPLICATED_INVENTORY = 1002002004,
  /** COORDINATOR_INVALID_PAYMENT - booking service payment */
  COORDINATOR_INVALID_PAYMENT = 1002003001,
  COORDINATOR_INVALID_BOOKING_STATUS = 1002003002,
  COORDINATOR_INVALID_PAYMENT_STATUS = 1002003003,
  COORDINATOR_NO_PAYMENT_INFO = 1002003004,
  COORDINATOR_EXCHANGERATE_NOT_BOUND_YET = 1002003005,
  COORDINATOR_NO_PAYMENT_TERM_INFO = 1002003006,
  /** COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET - booking service in-land port place management */
  COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET = 1002004001,
  /** CURRENCY_EXCHANGE_RATE_NOT_FOUND - currency desk */
  CURRENCY_EXCHANGE_RATE_NOT_FOUND = 1003001001,
  /** CARRIER_API_GATE_INVALID_PARAMETER - carrier api gate */
  CARRIER_API_GATE_INVALID_PARAMETER = 1004001001,
  CARRIER_API_GATE_INTERNAL_SERVER_ERROR = 1004001002,
  CARRIER_API_GATE_TOKEN_NOT_PROVIDED = 1004002001,
  CARRIER_API_GATE_TOKEN_INVALID = 1004002002,
  CARRIER_API_GATE_API_KEY_AUTHENTICATION_FAIL = 1004002003,
  CARRIER_API_GATE_API_KEY_REVOKED = 1004002004,
  CARRIER_API_GATE_API_KEY_USER_INACTIVE = 1004002005,
  CARRIER_API_GATE_API_KEY_PERMISSION_DENIED = 1004002006,
  /** API_GATEWAY_INVALID_PARAMETER - api gateway */
  API_GATEWAY_INVALID_PARAMETER = 1005001001,
  API_GATEWAY_INTERNAL_SERVER_ERROR = 1005001002,
  API_GATEWAY_REACH_QUOTE_LIMIT = 1005001003,
  API_GATEWAY_REACH_WEBHOOK_LIMIT = 1005001004,
  API_GATEWAY_RESOURCE_NOT_FOUND = 1005001005,
  API_GATEWAY_TOKEN_NOT_PROVIDED = 1005002001,
  API_GATEWAY_TOKEN_INVALID = 1005002002,
  API_GATEWAY_API_KEY_AUTHENTICATION_FAIL = 1005002003,
  API_GATEWAY_API_KEY_REVOKED = 1005002004,
  /** API_GATEWAY_CARRIER_API_KEY_DISABLED - The carrier API key is disabled by the operator of api-gateway. */
  API_GATEWAY_CARRIER_API_KEY_DISABLED = 1005002005,
  API_GATEWAY_API_KEY_PERMISSION_DENIED = 1005002006,
  /** PRICE_OPTIMIZER_INVALID_PARAMETER - price optimizer */
  PRICE_OPTIMIZER_INVALID_PARAMETER = 1006001001,
  PRICE_OPTIMIZER_UNSUPPORTED = 1006001002,
  PRICE_OPTIMIZER_DEADLINE_EXCEEDED = 1006002001,
  PRICE_OPTIMIZER_PREDICTOR_INTERNAL_ERROR = 1006002002,
  /** PAYMENT_GATE_INVALID_PARAMETER - payment gate */
  PAYMENT_GATE_INVALID_PARAMETER = 1007001001,
  PAYMENT_GATE_DATA_NOT_FOUND = 1007001002,
  PAYMENT_GATE_DUPLICATED_REQUEST_ID = 1007001003,
  PAYMENT_GATE_OPERATION_NOT_ALLOWED = 1007001004,
  PAYMENT_GATE_STALE_DATA = 1007001005,
  PAYMENT_GATE_DUPLICATED_BANK_ACCOUNT = 1007001006,
  /** AIRWALLEX_ADAPTER_INVALID_PARAMETER - airwallex adapter */
  AIRWALLEX_ADAPTER_INVALID_PARAMETER = 1008001001,
  AIRWALLEX_ADAPTER_INTERNAL_SERVER_ERROR = 1008001002,
  AIRWALLEX_ADAPTER_DATA_NOT_FOUND = 1008001003,
  AIRWALLEX_ADAPTER_OPERATION_NOT_ALLOWED = 1008001004,
  /** FILE_SERVICE_INVALID_PARAMETER - file service */
  FILE_SERVICE_INVALID_PARAMETER = 1009001001,
  FILE_SERVICE_EXCEED_SIZE_LIMIT = 1009001002,
  FILE_SERVICE_KEY_NOT_EXIST = 1009001003,
  /** EDI_INVALID_PARAMETER - EDI SVC */
  EDI_INVALID_PARAMETER = 1010001001,
  /** LOAN_CENTER_INVALID_PARAMETER - loan center */
  LOAN_CENTER_INVALID_PARAMETER = 1011001001,
  LOAN_CENTER_STALE_DATA = 1011001002,
  LOAN_CENTER_OPERATION_NOT_ALLOWED = 1011001003,
  LOAN_CENTER_LOAN_NOT_FOUND = 1011001004,
  LOAN_CENTER_LOAN_TERM_NOT_FOUND = 1011001005,
  LOAN_CENTER_CREDIT_DISABLED = 1011001006,
  LOAN_CENTER_CREDIT_INSUFFICIENT = 1011001007,
  LOAN_CENTER_CREDIT_NOT_FOUND = 1011001008,
  LOAN_CENTER_VENDOR_NOT_FOUND = 1011001009,
  LOAN_CENTER_REFERRAL_TERM_NOT_FOUND = 1011001010,
  LOAN_CENTER_COMMISSION_NOT_FOUND = 1011001011,
  LOAN_CENTER_DATA_NOT_FOUND = 1011001012,
  /** UNDERWRITING_SERVICE_INVALID_PARAMETER - Underwriting Service */
  UNDERWRITING_SERVICE_INVALID_PARAMETER = 1012001001,
  UNDERWRITING_SERVICE_STALE_DATA = 1012001002,
  UNDERWRITING_SERVICE_UNDERWRITING_NOT_FOUND = 1012001003,
  /** @deprecated */
  UNDERWRITING_SERVICE_ENROLL_ONGOING_OFAC_FAILED = 1012001004,
  UNDERWRITING_SERVICE_OPERATION_NOT_ALLOWED = 1012001005,
  UNDERWRITING_SERVICE_DATA_NOT_FOUND = 1012001006,
  UNDERWRITING_SERVICE_DATA_IN_SYNC = 1012001007,
  UNDERWRITING_SERVICE_DATA_NO_CHANGE = 1012001008,
  /** EULER_ADAPTER_INVALID_PARAMETER - EulerAdapter */
  EULER_ADAPTER_INVALID_PARAMETER = 1013001001,
  /** PLAID_ADAPTER_INVALID_PARAMETER - PlaidAdapter */
  PLAID_ADAPTER_INVALID_PARAMETER = 1014001001,
  PLAID_ADAPTER_INTERNAL_SERVER_ERROR = 1014001002,
  PLAID_ADAPTER_DATA_NOT_FOUND = 1014001003,
  PLAID_ADAPTER_OPERATION_NOT_ALLOWED = 1014001004,
  /** ALLOY_ADAPTER_INVALID_PARAMETER - AlloyAdapter */
  ALLOY_ADAPTER_INVALID_PARAMETER = 1015001001,
  /** STATUS_REPORTER_INVALID_PARAMETER - Status Reporter */
  STATUS_REPORTER_INVALID_PARAMETER = 1016000400,
  STATUS_REPORTER_RESOURCE_NOT_FOUND = 1016000404,
  STATUS_REPORTER_STALE_DATA = 1016000409,
  /** DWOLLA_ADAPTER_INVALID_PARAMETER - Dwolla Adapter */
  DWOLLA_ADAPTER_INVALID_PARAMETER = 1017001001,
  DWOLLA_ADAPTER_INTERNAL_SERVER_ERROR = 1017001002,
  DWOLLA_ADAPTER_DATA_NOT_FOUND = 1017001003,
  DWOLLA_ADAPTER_DUPLICATED_FUNDING_SOURCE = 1017001004,
  DWOLLA_ADAPTER_REACH_FUNDING_SOURCE_LIMIT = 1017001005,
  DWOLLA_ADAPTER_MICRO_DEPOSIT_ALREADY_INITIATED = 1017001006,
  DWOLLA_ADAPTER_TRY_AGAIN_LATER = 1017001007,
  DWOLLA_ADAPTER_TOO_MANY_ATTEMPTS = 1017001008,
  DWOLLA_ADAPTER_BANK_ALREADY_VERIFIED = 1017001009,
  DWOLLA_ADAPTER_WRONG_AMOUNT = 1017001010,
  DWOLLA_ADAPTER_MICRO_DEPOSIT_NOT_INITIATED = 1017001011,
  /** DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED - This code will appear at PlatformBankAccount.dwolla_meta_data.last_verification_error.code. */
  DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED = 1017001012,
  DWOLLA_ADAPTER_NO_VERIFY_MICRO_DEPOSIT_LINK = 1017001013,
  /** HELLO_SIGN_ADAPTER_INVALID_PARAMETER - Hello Sign Adapter */
  HELLO_SIGN_ADAPTER_INVALID_PARAMETER = 1018001001,
  HELLO_SIGN_ADAPTER_INTERNAL_SERVER_ERROR = 1018001002,
  HELLO_SIGN_ADAPTER_STALE_DATA = 1018001003,
  HELLO_SIGN_ADAPTER_DATA_NOT_FOUND = 1018001004,
  /** DOCU_SUM_INVALID_PARAMETER - DocuSum */
  DOCU_SUM_INVALID_PARAMETER = 1019001001,
  DOCU_SUM_DATA_NOT_FOUND = 1019001002,
  DOCU_SUM_OPERATION_NOT_ALLOWED = 1019001003,
  DOCU_SUM_STALE_DATA = 1019001004,
  /** DOCU_HOG_INVALID_PARAMETER - DocuHog */
  DOCU_HOG_INVALID_PARAMETER = 1020001001,
  DOCU_HOG_DATA_NOT_FOUND = 1020001002,
  DOCU_HOG_CONFLICT_DATA = 1020001003,
  /** DOCU_VAULT_INVALID_PARAMETER - DocuVault */
  DOCU_VAULT_INVALID_PARAMETER = 1021001001,
  DOCU_VAULT_DATA_NOT_FOUND = 1021001002,
  DOCU_VAULT_CONFLICT_DATA = 1021001003,
  UNRECOGNIZED = -1,
}

export function error_ErrorCodeFromJSON(object: any): Error_ErrorCode {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return Error_ErrorCode.UNKNOWN;
    case 1001000400:
    case "PREBOOKING_INVALID_PARAMETER":
      return Error_ErrorCode.PREBOOKING_INVALID_PARAMETER;
    case 1001000404:
    case "PREBOOKING_QUOTE_NOT_FOUND":
      return Error_ErrorCode.PREBOOKING_QUOTE_NOT_FOUND;
    case 1002001001:
    case "COORDINATOR_INVALID_BOOKING_ID":
      return Error_ErrorCode.COORDINATOR_INVALID_BOOKING_ID;
    case 1002001002:
    case "COORDINATOR_VALIDATION_FAILED":
      return Error_ErrorCode.COORDINATOR_VALIDATION_FAILED;
    case 1002001003:
    case "COORDINATOR_INVALID_PARAMETER":
      return Error_ErrorCode.COORDINATOR_INVALID_PARAMETER;
    case 1002001004:
    case "COORDINATOR_BOOKING_NOT_FOUND":
      return Error_ErrorCode.COORDINATOR_BOOKING_NOT_FOUND;
    case 1002001005:
    case "COORDINATOR_BOOKING_QUOTE_EXPIRED":
      return Error_ErrorCode.COORDINATOR_BOOKING_QUOTE_EXPIRED;
    case 1002002001:
    case "COORDINATOR_INVALID_INVENTORY":
      return Error_ErrorCode.COORDINATOR_INVALID_INVENTORY;
    case 1002002002:
    case "COORDINATOR_INSUFFICIENT_INVENTORY":
      return Error_ErrorCode.COORDINATOR_INSUFFICIENT_INVENTORY;
    case 1002002003:
    case "COORDINATOR_OVER_BOOKING_CLOSING_TIME":
      return Error_ErrorCode.COORDINATOR_OVER_BOOKING_CLOSING_TIME;
    case 1002002004:
    case "COORDINATOR_DUPLICATED_INVENTORY":
      return Error_ErrorCode.COORDINATOR_DUPLICATED_INVENTORY;
    case 1002003001:
    case "COORDINATOR_INVALID_PAYMENT":
      return Error_ErrorCode.COORDINATOR_INVALID_PAYMENT;
    case 1002003002:
    case "COORDINATOR_INVALID_BOOKING_STATUS":
      return Error_ErrorCode.COORDINATOR_INVALID_BOOKING_STATUS;
    case 1002003003:
    case "COORDINATOR_INVALID_PAYMENT_STATUS":
      return Error_ErrorCode.COORDINATOR_INVALID_PAYMENT_STATUS;
    case 1002003004:
    case "COORDINATOR_NO_PAYMENT_INFO":
      return Error_ErrorCode.COORDINATOR_NO_PAYMENT_INFO;
    case 1002003005:
    case "COORDINATOR_EXCHANGERATE_NOT_BOUND_YET":
      return Error_ErrorCode.COORDINATOR_EXCHANGERATE_NOT_BOUND_YET;
    case 1002003006:
    case "COORDINATOR_NO_PAYMENT_TERM_INFO":
      return Error_ErrorCode.COORDINATOR_NO_PAYMENT_TERM_INFO;
    case 1002004001:
    case "COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET":
      return Error_ErrorCode.COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET;
    case 1003001001:
    case "CURRENCY_EXCHANGE_RATE_NOT_FOUND":
      return Error_ErrorCode.CURRENCY_EXCHANGE_RATE_NOT_FOUND;
    case 1004001001:
    case "CARRIER_API_GATE_INVALID_PARAMETER":
      return Error_ErrorCode.CARRIER_API_GATE_INVALID_PARAMETER;
    case 1004001002:
    case "CARRIER_API_GATE_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.CARRIER_API_GATE_INTERNAL_SERVER_ERROR;
    case 1004002001:
    case "CARRIER_API_GATE_TOKEN_NOT_PROVIDED":
      return Error_ErrorCode.CARRIER_API_GATE_TOKEN_NOT_PROVIDED;
    case 1004002002:
    case "CARRIER_API_GATE_TOKEN_INVALID":
      return Error_ErrorCode.CARRIER_API_GATE_TOKEN_INVALID;
    case 1004002003:
    case "CARRIER_API_GATE_API_KEY_AUTHENTICATION_FAIL":
      return Error_ErrorCode.CARRIER_API_GATE_API_KEY_AUTHENTICATION_FAIL;
    case 1004002004:
    case "CARRIER_API_GATE_API_KEY_REVOKED":
      return Error_ErrorCode.CARRIER_API_GATE_API_KEY_REVOKED;
    case 1004002005:
    case "CARRIER_API_GATE_API_KEY_USER_INACTIVE":
      return Error_ErrorCode.CARRIER_API_GATE_API_KEY_USER_INACTIVE;
    case 1004002006:
    case "CARRIER_API_GATE_API_KEY_PERMISSION_DENIED":
      return Error_ErrorCode.CARRIER_API_GATE_API_KEY_PERMISSION_DENIED;
    case 1005001001:
    case "API_GATEWAY_INVALID_PARAMETER":
      return Error_ErrorCode.API_GATEWAY_INVALID_PARAMETER;
    case 1005001002:
    case "API_GATEWAY_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.API_GATEWAY_INTERNAL_SERVER_ERROR;
    case 1005001003:
    case "API_GATEWAY_REACH_QUOTE_LIMIT":
      return Error_ErrorCode.API_GATEWAY_REACH_QUOTE_LIMIT;
    case 1005001004:
    case "API_GATEWAY_REACH_WEBHOOK_LIMIT":
      return Error_ErrorCode.API_GATEWAY_REACH_WEBHOOK_LIMIT;
    case 1005001005:
    case "API_GATEWAY_RESOURCE_NOT_FOUND":
      return Error_ErrorCode.API_GATEWAY_RESOURCE_NOT_FOUND;
    case 1005002001:
    case "API_GATEWAY_TOKEN_NOT_PROVIDED":
      return Error_ErrorCode.API_GATEWAY_TOKEN_NOT_PROVIDED;
    case 1005002002:
    case "API_GATEWAY_TOKEN_INVALID":
      return Error_ErrorCode.API_GATEWAY_TOKEN_INVALID;
    case 1005002003:
    case "API_GATEWAY_API_KEY_AUTHENTICATION_FAIL":
      return Error_ErrorCode.API_GATEWAY_API_KEY_AUTHENTICATION_FAIL;
    case 1005002004:
    case "API_GATEWAY_API_KEY_REVOKED":
      return Error_ErrorCode.API_GATEWAY_API_KEY_REVOKED;
    case 1005002005:
    case "API_GATEWAY_CARRIER_API_KEY_DISABLED":
      return Error_ErrorCode.API_GATEWAY_CARRIER_API_KEY_DISABLED;
    case 1005002006:
    case "API_GATEWAY_API_KEY_PERMISSION_DENIED":
      return Error_ErrorCode.API_GATEWAY_API_KEY_PERMISSION_DENIED;
    case 1006001001:
    case "PRICE_OPTIMIZER_INVALID_PARAMETER":
      return Error_ErrorCode.PRICE_OPTIMIZER_INVALID_PARAMETER;
    case 1006001002:
    case "PRICE_OPTIMIZER_UNSUPPORTED":
      return Error_ErrorCode.PRICE_OPTIMIZER_UNSUPPORTED;
    case 1006002001:
    case "PRICE_OPTIMIZER_DEADLINE_EXCEEDED":
      return Error_ErrorCode.PRICE_OPTIMIZER_DEADLINE_EXCEEDED;
    case 1006002002:
    case "PRICE_OPTIMIZER_PREDICTOR_INTERNAL_ERROR":
      return Error_ErrorCode.PRICE_OPTIMIZER_PREDICTOR_INTERNAL_ERROR;
    case 1007001001:
    case "PAYMENT_GATE_INVALID_PARAMETER":
      return Error_ErrorCode.PAYMENT_GATE_INVALID_PARAMETER;
    case 1007001002:
    case "PAYMENT_GATE_DATA_NOT_FOUND":
      return Error_ErrorCode.PAYMENT_GATE_DATA_NOT_FOUND;
    case 1007001003:
    case "PAYMENT_GATE_DUPLICATED_REQUEST_ID":
      return Error_ErrorCode.PAYMENT_GATE_DUPLICATED_REQUEST_ID;
    case 1007001004:
    case "PAYMENT_GATE_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.PAYMENT_GATE_OPERATION_NOT_ALLOWED;
    case 1007001005:
    case "PAYMENT_GATE_STALE_DATA":
      return Error_ErrorCode.PAYMENT_GATE_STALE_DATA;
    case 1007001006:
    case "PAYMENT_GATE_DUPLICATED_BANK_ACCOUNT":
      return Error_ErrorCode.PAYMENT_GATE_DUPLICATED_BANK_ACCOUNT;
    case 1008001001:
    case "AIRWALLEX_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.AIRWALLEX_ADAPTER_INVALID_PARAMETER;
    case 1008001002:
    case "AIRWALLEX_ADAPTER_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.AIRWALLEX_ADAPTER_INTERNAL_SERVER_ERROR;
    case 1008001003:
    case "AIRWALLEX_ADAPTER_DATA_NOT_FOUND":
      return Error_ErrorCode.AIRWALLEX_ADAPTER_DATA_NOT_FOUND;
    case 1008001004:
    case "AIRWALLEX_ADAPTER_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.AIRWALLEX_ADAPTER_OPERATION_NOT_ALLOWED;
    case 1009001001:
    case "FILE_SERVICE_INVALID_PARAMETER":
      return Error_ErrorCode.FILE_SERVICE_INVALID_PARAMETER;
    case 1009001002:
    case "FILE_SERVICE_EXCEED_SIZE_LIMIT":
      return Error_ErrorCode.FILE_SERVICE_EXCEED_SIZE_LIMIT;
    case 1009001003:
    case "FILE_SERVICE_KEY_NOT_EXIST":
      return Error_ErrorCode.FILE_SERVICE_KEY_NOT_EXIST;
    case 1010001001:
    case "EDI_INVALID_PARAMETER":
      return Error_ErrorCode.EDI_INVALID_PARAMETER;
    case 1011001001:
    case "LOAN_CENTER_INVALID_PARAMETER":
      return Error_ErrorCode.LOAN_CENTER_INVALID_PARAMETER;
    case 1011001002:
    case "LOAN_CENTER_STALE_DATA":
      return Error_ErrorCode.LOAN_CENTER_STALE_DATA;
    case 1011001003:
    case "LOAN_CENTER_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.LOAN_CENTER_OPERATION_NOT_ALLOWED;
    case 1011001004:
    case "LOAN_CENTER_LOAN_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_LOAN_NOT_FOUND;
    case 1011001005:
    case "LOAN_CENTER_LOAN_TERM_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_LOAN_TERM_NOT_FOUND;
    case 1011001006:
    case "LOAN_CENTER_CREDIT_DISABLED":
      return Error_ErrorCode.LOAN_CENTER_CREDIT_DISABLED;
    case 1011001007:
    case "LOAN_CENTER_CREDIT_INSUFFICIENT":
      return Error_ErrorCode.LOAN_CENTER_CREDIT_INSUFFICIENT;
    case 1011001008:
    case "LOAN_CENTER_CREDIT_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_CREDIT_NOT_FOUND;
    case 1011001009:
    case "LOAN_CENTER_VENDOR_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_VENDOR_NOT_FOUND;
    case 1011001010:
    case "LOAN_CENTER_REFERRAL_TERM_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_REFERRAL_TERM_NOT_FOUND;
    case 1011001011:
    case "LOAN_CENTER_COMMISSION_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_COMMISSION_NOT_FOUND;
    case 1011001012:
    case "LOAN_CENTER_DATA_NOT_FOUND":
      return Error_ErrorCode.LOAN_CENTER_DATA_NOT_FOUND;
    case 1012001001:
    case "UNDERWRITING_SERVICE_INVALID_PARAMETER":
      return Error_ErrorCode.UNDERWRITING_SERVICE_INVALID_PARAMETER;
    case 1012001002:
    case "UNDERWRITING_SERVICE_STALE_DATA":
      return Error_ErrorCode.UNDERWRITING_SERVICE_STALE_DATA;
    case 1012001003:
    case "UNDERWRITING_SERVICE_UNDERWRITING_NOT_FOUND":
      return Error_ErrorCode.UNDERWRITING_SERVICE_UNDERWRITING_NOT_FOUND;
    case 1012001004:
    case "UNDERWRITING_SERVICE_ENROLL_ONGOING_OFAC_FAILED":
      return Error_ErrorCode.UNDERWRITING_SERVICE_ENROLL_ONGOING_OFAC_FAILED;
    case 1012001005:
    case "UNDERWRITING_SERVICE_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.UNDERWRITING_SERVICE_OPERATION_NOT_ALLOWED;
    case 1012001006:
    case "UNDERWRITING_SERVICE_DATA_NOT_FOUND":
      return Error_ErrorCode.UNDERWRITING_SERVICE_DATA_NOT_FOUND;
    case 1012001007:
    case "UNDERWRITING_SERVICE_DATA_IN_SYNC":
      return Error_ErrorCode.UNDERWRITING_SERVICE_DATA_IN_SYNC;
    case 1012001008:
    case "UNDERWRITING_SERVICE_DATA_NO_CHANGE":
      return Error_ErrorCode.UNDERWRITING_SERVICE_DATA_NO_CHANGE;
    case 1013001001:
    case "EULER_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.EULER_ADAPTER_INVALID_PARAMETER;
    case 1014001001:
    case "PLAID_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.PLAID_ADAPTER_INVALID_PARAMETER;
    case 1014001002:
    case "PLAID_ADAPTER_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.PLAID_ADAPTER_INTERNAL_SERVER_ERROR;
    case 1014001003:
    case "PLAID_ADAPTER_DATA_NOT_FOUND":
      return Error_ErrorCode.PLAID_ADAPTER_DATA_NOT_FOUND;
    case 1014001004:
    case "PLAID_ADAPTER_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.PLAID_ADAPTER_OPERATION_NOT_ALLOWED;
    case 1015001001:
    case "ALLOY_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.ALLOY_ADAPTER_INVALID_PARAMETER;
    case 1016000400:
    case "STATUS_REPORTER_INVALID_PARAMETER":
      return Error_ErrorCode.STATUS_REPORTER_INVALID_PARAMETER;
    case 1016000404:
    case "STATUS_REPORTER_RESOURCE_NOT_FOUND":
      return Error_ErrorCode.STATUS_REPORTER_RESOURCE_NOT_FOUND;
    case 1016000409:
    case "STATUS_REPORTER_STALE_DATA":
      return Error_ErrorCode.STATUS_REPORTER_STALE_DATA;
    case 1017001001:
    case "DWOLLA_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.DWOLLA_ADAPTER_INVALID_PARAMETER;
    case 1017001002:
    case "DWOLLA_ADAPTER_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.DWOLLA_ADAPTER_INTERNAL_SERVER_ERROR;
    case 1017001003:
    case "DWOLLA_ADAPTER_DATA_NOT_FOUND":
      return Error_ErrorCode.DWOLLA_ADAPTER_DATA_NOT_FOUND;
    case 1017001004:
    case "DWOLLA_ADAPTER_DUPLICATED_FUNDING_SOURCE":
      return Error_ErrorCode.DWOLLA_ADAPTER_DUPLICATED_FUNDING_SOURCE;
    case 1017001005:
    case "DWOLLA_ADAPTER_REACH_FUNDING_SOURCE_LIMIT":
      return Error_ErrorCode.DWOLLA_ADAPTER_REACH_FUNDING_SOURCE_LIMIT;
    case 1017001006:
    case "DWOLLA_ADAPTER_MICRO_DEPOSIT_ALREADY_INITIATED":
      return Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_ALREADY_INITIATED;
    case 1017001007:
    case "DWOLLA_ADAPTER_TRY_AGAIN_LATER":
      return Error_ErrorCode.DWOLLA_ADAPTER_TRY_AGAIN_LATER;
    case 1017001008:
    case "DWOLLA_ADAPTER_TOO_MANY_ATTEMPTS":
      return Error_ErrorCode.DWOLLA_ADAPTER_TOO_MANY_ATTEMPTS;
    case 1017001009:
    case "DWOLLA_ADAPTER_BANK_ALREADY_VERIFIED":
      return Error_ErrorCode.DWOLLA_ADAPTER_BANK_ALREADY_VERIFIED;
    case 1017001010:
    case "DWOLLA_ADAPTER_WRONG_AMOUNT":
      return Error_ErrorCode.DWOLLA_ADAPTER_WRONG_AMOUNT;
    case 1017001011:
    case "DWOLLA_ADAPTER_MICRO_DEPOSIT_NOT_INITIATED":
      return Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_NOT_INITIATED;
    case 1017001012:
    case "DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED":
      return Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED;
    case 1017001013:
    case "DWOLLA_ADAPTER_NO_VERIFY_MICRO_DEPOSIT_LINK":
      return Error_ErrorCode.DWOLLA_ADAPTER_NO_VERIFY_MICRO_DEPOSIT_LINK;
    case 1018001001:
    case "HELLO_SIGN_ADAPTER_INVALID_PARAMETER":
      return Error_ErrorCode.HELLO_SIGN_ADAPTER_INVALID_PARAMETER;
    case 1018001002:
    case "HELLO_SIGN_ADAPTER_INTERNAL_SERVER_ERROR":
      return Error_ErrorCode.HELLO_SIGN_ADAPTER_INTERNAL_SERVER_ERROR;
    case 1018001003:
    case "HELLO_SIGN_ADAPTER_STALE_DATA":
      return Error_ErrorCode.HELLO_SIGN_ADAPTER_STALE_DATA;
    case 1018001004:
    case "HELLO_SIGN_ADAPTER_DATA_NOT_FOUND":
      return Error_ErrorCode.HELLO_SIGN_ADAPTER_DATA_NOT_FOUND;
    case 1019001001:
    case "DOCU_SUM_INVALID_PARAMETER":
      return Error_ErrorCode.DOCU_SUM_INVALID_PARAMETER;
    case 1019001002:
    case "DOCU_SUM_DATA_NOT_FOUND":
      return Error_ErrorCode.DOCU_SUM_DATA_NOT_FOUND;
    case 1019001003:
    case "DOCU_SUM_OPERATION_NOT_ALLOWED":
      return Error_ErrorCode.DOCU_SUM_OPERATION_NOT_ALLOWED;
    case 1019001004:
    case "DOCU_SUM_STALE_DATA":
      return Error_ErrorCode.DOCU_SUM_STALE_DATA;
    case 1020001001:
    case "DOCU_HOG_INVALID_PARAMETER":
      return Error_ErrorCode.DOCU_HOG_INVALID_PARAMETER;
    case 1020001002:
    case "DOCU_HOG_DATA_NOT_FOUND":
      return Error_ErrorCode.DOCU_HOG_DATA_NOT_FOUND;
    case 1020001003:
    case "DOCU_HOG_CONFLICT_DATA":
      return Error_ErrorCode.DOCU_HOG_CONFLICT_DATA;
    case 1021001001:
    case "DOCU_VAULT_INVALID_PARAMETER":
      return Error_ErrorCode.DOCU_VAULT_INVALID_PARAMETER;
    case 1021001002:
    case "DOCU_VAULT_DATA_NOT_FOUND":
      return Error_ErrorCode.DOCU_VAULT_DATA_NOT_FOUND;
    case 1021001003:
    case "DOCU_VAULT_CONFLICT_DATA":
      return Error_ErrorCode.DOCU_VAULT_CONFLICT_DATA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Error_ErrorCode.UNRECOGNIZED;
  }
}

export function error_ErrorCodeToJSON(object: Error_ErrorCode): string {
  switch (object) {
    case Error_ErrorCode.UNKNOWN:
      return "UNKNOWN";
    case Error_ErrorCode.PREBOOKING_INVALID_PARAMETER:
      return "PREBOOKING_INVALID_PARAMETER";
    case Error_ErrorCode.PREBOOKING_QUOTE_NOT_FOUND:
      return "PREBOOKING_QUOTE_NOT_FOUND";
    case Error_ErrorCode.COORDINATOR_INVALID_BOOKING_ID:
      return "COORDINATOR_INVALID_BOOKING_ID";
    case Error_ErrorCode.COORDINATOR_VALIDATION_FAILED:
      return "COORDINATOR_VALIDATION_FAILED";
    case Error_ErrorCode.COORDINATOR_INVALID_PARAMETER:
      return "COORDINATOR_INVALID_PARAMETER";
    case Error_ErrorCode.COORDINATOR_BOOKING_NOT_FOUND:
      return "COORDINATOR_BOOKING_NOT_FOUND";
    case Error_ErrorCode.COORDINATOR_BOOKING_QUOTE_EXPIRED:
      return "COORDINATOR_BOOKING_QUOTE_EXPIRED";
    case Error_ErrorCode.COORDINATOR_INVALID_INVENTORY:
      return "COORDINATOR_INVALID_INVENTORY";
    case Error_ErrorCode.COORDINATOR_INSUFFICIENT_INVENTORY:
      return "COORDINATOR_INSUFFICIENT_INVENTORY";
    case Error_ErrorCode.COORDINATOR_OVER_BOOKING_CLOSING_TIME:
      return "COORDINATOR_OVER_BOOKING_CLOSING_TIME";
    case Error_ErrorCode.COORDINATOR_DUPLICATED_INVENTORY:
      return "COORDINATOR_DUPLICATED_INVENTORY";
    case Error_ErrorCode.COORDINATOR_INVALID_PAYMENT:
      return "COORDINATOR_INVALID_PAYMENT";
    case Error_ErrorCode.COORDINATOR_INVALID_BOOKING_STATUS:
      return "COORDINATOR_INVALID_BOOKING_STATUS";
    case Error_ErrorCode.COORDINATOR_INVALID_PAYMENT_STATUS:
      return "COORDINATOR_INVALID_PAYMENT_STATUS";
    case Error_ErrorCode.COORDINATOR_NO_PAYMENT_INFO:
      return "COORDINATOR_NO_PAYMENT_INFO";
    case Error_ErrorCode.COORDINATOR_EXCHANGERATE_NOT_BOUND_YET:
      return "COORDINATOR_EXCHANGERATE_NOT_BOUND_YET";
    case Error_ErrorCode.COORDINATOR_NO_PAYMENT_TERM_INFO:
      return "COORDINATOR_NO_PAYMENT_TERM_INFO";
    case Error_ErrorCode.COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET:
      return "COORDINATOR_INVALID_INLAND_PORT_PLACE_SHEET";
    case Error_ErrorCode.CURRENCY_EXCHANGE_RATE_NOT_FOUND:
      return "CURRENCY_EXCHANGE_RATE_NOT_FOUND";
    case Error_ErrorCode.CARRIER_API_GATE_INVALID_PARAMETER:
      return "CARRIER_API_GATE_INVALID_PARAMETER";
    case Error_ErrorCode.CARRIER_API_GATE_INTERNAL_SERVER_ERROR:
      return "CARRIER_API_GATE_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.CARRIER_API_GATE_TOKEN_NOT_PROVIDED:
      return "CARRIER_API_GATE_TOKEN_NOT_PROVIDED";
    case Error_ErrorCode.CARRIER_API_GATE_TOKEN_INVALID:
      return "CARRIER_API_GATE_TOKEN_INVALID";
    case Error_ErrorCode.CARRIER_API_GATE_API_KEY_AUTHENTICATION_FAIL:
      return "CARRIER_API_GATE_API_KEY_AUTHENTICATION_FAIL";
    case Error_ErrorCode.CARRIER_API_GATE_API_KEY_REVOKED:
      return "CARRIER_API_GATE_API_KEY_REVOKED";
    case Error_ErrorCode.CARRIER_API_GATE_API_KEY_USER_INACTIVE:
      return "CARRIER_API_GATE_API_KEY_USER_INACTIVE";
    case Error_ErrorCode.CARRIER_API_GATE_API_KEY_PERMISSION_DENIED:
      return "CARRIER_API_GATE_API_KEY_PERMISSION_DENIED";
    case Error_ErrorCode.API_GATEWAY_INVALID_PARAMETER:
      return "API_GATEWAY_INVALID_PARAMETER";
    case Error_ErrorCode.API_GATEWAY_INTERNAL_SERVER_ERROR:
      return "API_GATEWAY_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.API_GATEWAY_REACH_QUOTE_LIMIT:
      return "API_GATEWAY_REACH_QUOTE_LIMIT";
    case Error_ErrorCode.API_GATEWAY_REACH_WEBHOOK_LIMIT:
      return "API_GATEWAY_REACH_WEBHOOK_LIMIT";
    case Error_ErrorCode.API_GATEWAY_RESOURCE_NOT_FOUND:
      return "API_GATEWAY_RESOURCE_NOT_FOUND";
    case Error_ErrorCode.API_GATEWAY_TOKEN_NOT_PROVIDED:
      return "API_GATEWAY_TOKEN_NOT_PROVIDED";
    case Error_ErrorCode.API_GATEWAY_TOKEN_INVALID:
      return "API_GATEWAY_TOKEN_INVALID";
    case Error_ErrorCode.API_GATEWAY_API_KEY_AUTHENTICATION_FAIL:
      return "API_GATEWAY_API_KEY_AUTHENTICATION_FAIL";
    case Error_ErrorCode.API_GATEWAY_API_KEY_REVOKED:
      return "API_GATEWAY_API_KEY_REVOKED";
    case Error_ErrorCode.API_GATEWAY_CARRIER_API_KEY_DISABLED:
      return "API_GATEWAY_CARRIER_API_KEY_DISABLED";
    case Error_ErrorCode.API_GATEWAY_API_KEY_PERMISSION_DENIED:
      return "API_GATEWAY_API_KEY_PERMISSION_DENIED";
    case Error_ErrorCode.PRICE_OPTIMIZER_INVALID_PARAMETER:
      return "PRICE_OPTIMIZER_INVALID_PARAMETER";
    case Error_ErrorCode.PRICE_OPTIMIZER_UNSUPPORTED:
      return "PRICE_OPTIMIZER_UNSUPPORTED";
    case Error_ErrorCode.PRICE_OPTIMIZER_DEADLINE_EXCEEDED:
      return "PRICE_OPTIMIZER_DEADLINE_EXCEEDED";
    case Error_ErrorCode.PRICE_OPTIMIZER_PREDICTOR_INTERNAL_ERROR:
      return "PRICE_OPTIMIZER_PREDICTOR_INTERNAL_ERROR";
    case Error_ErrorCode.PAYMENT_GATE_INVALID_PARAMETER:
      return "PAYMENT_GATE_INVALID_PARAMETER";
    case Error_ErrorCode.PAYMENT_GATE_DATA_NOT_FOUND:
      return "PAYMENT_GATE_DATA_NOT_FOUND";
    case Error_ErrorCode.PAYMENT_GATE_DUPLICATED_REQUEST_ID:
      return "PAYMENT_GATE_DUPLICATED_REQUEST_ID";
    case Error_ErrorCode.PAYMENT_GATE_OPERATION_NOT_ALLOWED:
      return "PAYMENT_GATE_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.PAYMENT_GATE_STALE_DATA:
      return "PAYMENT_GATE_STALE_DATA";
    case Error_ErrorCode.PAYMENT_GATE_DUPLICATED_BANK_ACCOUNT:
      return "PAYMENT_GATE_DUPLICATED_BANK_ACCOUNT";
    case Error_ErrorCode.AIRWALLEX_ADAPTER_INVALID_PARAMETER:
      return "AIRWALLEX_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.AIRWALLEX_ADAPTER_INTERNAL_SERVER_ERROR:
      return "AIRWALLEX_ADAPTER_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.AIRWALLEX_ADAPTER_DATA_NOT_FOUND:
      return "AIRWALLEX_ADAPTER_DATA_NOT_FOUND";
    case Error_ErrorCode.AIRWALLEX_ADAPTER_OPERATION_NOT_ALLOWED:
      return "AIRWALLEX_ADAPTER_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.FILE_SERVICE_INVALID_PARAMETER:
      return "FILE_SERVICE_INVALID_PARAMETER";
    case Error_ErrorCode.FILE_SERVICE_EXCEED_SIZE_LIMIT:
      return "FILE_SERVICE_EXCEED_SIZE_LIMIT";
    case Error_ErrorCode.FILE_SERVICE_KEY_NOT_EXIST:
      return "FILE_SERVICE_KEY_NOT_EXIST";
    case Error_ErrorCode.EDI_INVALID_PARAMETER:
      return "EDI_INVALID_PARAMETER";
    case Error_ErrorCode.LOAN_CENTER_INVALID_PARAMETER:
      return "LOAN_CENTER_INVALID_PARAMETER";
    case Error_ErrorCode.LOAN_CENTER_STALE_DATA:
      return "LOAN_CENTER_STALE_DATA";
    case Error_ErrorCode.LOAN_CENTER_OPERATION_NOT_ALLOWED:
      return "LOAN_CENTER_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.LOAN_CENTER_LOAN_NOT_FOUND:
      return "LOAN_CENTER_LOAN_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_LOAN_TERM_NOT_FOUND:
      return "LOAN_CENTER_LOAN_TERM_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_CREDIT_DISABLED:
      return "LOAN_CENTER_CREDIT_DISABLED";
    case Error_ErrorCode.LOAN_CENTER_CREDIT_INSUFFICIENT:
      return "LOAN_CENTER_CREDIT_INSUFFICIENT";
    case Error_ErrorCode.LOAN_CENTER_CREDIT_NOT_FOUND:
      return "LOAN_CENTER_CREDIT_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_VENDOR_NOT_FOUND:
      return "LOAN_CENTER_VENDOR_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_REFERRAL_TERM_NOT_FOUND:
      return "LOAN_CENTER_REFERRAL_TERM_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_COMMISSION_NOT_FOUND:
      return "LOAN_CENTER_COMMISSION_NOT_FOUND";
    case Error_ErrorCode.LOAN_CENTER_DATA_NOT_FOUND:
      return "LOAN_CENTER_DATA_NOT_FOUND";
    case Error_ErrorCode.UNDERWRITING_SERVICE_INVALID_PARAMETER:
      return "UNDERWRITING_SERVICE_INVALID_PARAMETER";
    case Error_ErrorCode.UNDERWRITING_SERVICE_STALE_DATA:
      return "UNDERWRITING_SERVICE_STALE_DATA";
    case Error_ErrorCode.UNDERWRITING_SERVICE_UNDERWRITING_NOT_FOUND:
      return "UNDERWRITING_SERVICE_UNDERWRITING_NOT_FOUND";
    case Error_ErrorCode.UNDERWRITING_SERVICE_ENROLL_ONGOING_OFAC_FAILED:
      return "UNDERWRITING_SERVICE_ENROLL_ONGOING_OFAC_FAILED";
    case Error_ErrorCode.UNDERWRITING_SERVICE_OPERATION_NOT_ALLOWED:
      return "UNDERWRITING_SERVICE_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.UNDERWRITING_SERVICE_DATA_NOT_FOUND:
      return "UNDERWRITING_SERVICE_DATA_NOT_FOUND";
    case Error_ErrorCode.UNDERWRITING_SERVICE_DATA_IN_SYNC:
      return "UNDERWRITING_SERVICE_DATA_IN_SYNC";
    case Error_ErrorCode.UNDERWRITING_SERVICE_DATA_NO_CHANGE:
      return "UNDERWRITING_SERVICE_DATA_NO_CHANGE";
    case Error_ErrorCode.EULER_ADAPTER_INVALID_PARAMETER:
      return "EULER_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.PLAID_ADAPTER_INVALID_PARAMETER:
      return "PLAID_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.PLAID_ADAPTER_INTERNAL_SERVER_ERROR:
      return "PLAID_ADAPTER_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.PLAID_ADAPTER_DATA_NOT_FOUND:
      return "PLAID_ADAPTER_DATA_NOT_FOUND";
    case Error_ErrorCode.PLAID_ADAPTER_OPERATION_NOT_ALLOWED:
      return "PLAID_ADAPTER_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.ALLOY_ADAPTER_INVALID_PARAMETER:
      return "ALLOY_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.STATUS_REPORTER_INVALID_PARAMETER:
      return "STATUS_REPORTER_INVALID_PARAMETER";
    case Error_ErrorCode.STATUS_REPORTER_RESOURCE_NOT_FOUND:
      return "STATUS_REPORTER_RESOURCE_NOT_FOUND";
    case Error_ErrorCode.STATUS_REPORTER_STALE_DATA:
      return "STATUS_REPORTER_STALE_DATA";
    case Error_ErrorCode.DWOLLA_ADAPTER_INVALID_PARAMETER:
      return "DWOLLA_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.DWOLLA_ADAPTER_INTERNAL_SERVER_ERROR:
      return "DWOLLA_ADAPTER_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.DWOLLA_ADAPTER_DATA_NOT_FOUND:
      return "DWOLLA_ADAPTER_DATA_NOT_FOUND";
    case Error_ErrorCode.DWOLLA_ADAPTER_DUPLICATED_FUNDING_SOURCE:
      return "DWOLLA_ADAPTER_DUPLICATED_FUNDING_SOURCE";
    case Error_ErrorCode.DWOLLA_ADAPTER_REACH_FUNDING_SOURCE_LIMIT:
      return "DWOLLA_ADAPTER_REACH_FUNDING_SOURCE_LIMIT";
    case Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_ALREADY_INITIATED:
      return "DWOLLA_ADAPTER_MICRO_DEPOSIT_ALREADY_INITIATED";
    case Error_ErrorCode.DWOLLA_ADAPTER_TRY_AGAIN_LATER:
      return "DWOLLA_ADAPTER_TRY_AGAIN_LATER";
    case Error_ErrorCode.DWOLLA_ADAPTER_TOO_MANY_ATTEMPTS:
      return "DWOLLA_ADAPTER_TOO_MANY_ATTEMPTS";
    case Error_ErrorCode.DWOLLA_ADAPTER_BANK_ALREADY_VERIFIED:
      return "DWOLLA_ADAPTER_BANK_ALREADY_VERIFIED";
    case Error_ErrorCode.DWOLLA_ADAPTER_WRONG_AMOUNT:
      return "DWOLLA_ADAPTER_WRONG_AMOUNT";
    case Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_NOT_INITIATED:
      return "DWOLLA_ADAPTER_MICRO_DEPOSIT_NOT_INITIATED";
    case Error_ErrorCode.DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED:
      return "DWOLLA_ADAPTER_MICRO_DEPOSIT_FAILED";
    case Error_ErrorCode.DWOLLA_ADAPTER_NO_VERIFY_MICRO_DEPOSIT_LINK:
      return "DWOLLA_ADAPTER_NO_VERIFY_MICRO_DEPOSIT_LINK";
    case Error_ErrorCode.HELLO_SIGN_ADAPTER_INVALID_PARAMETER:
      return "HELLO_SIGN_ADAPTER_INVALID_PARAMETER";
    case Error_ErrorCode.HELLO_SIGN_ADAPTER_INTERNAL_SERVER_ERROR:
      return "HELLO_SIGN_ADAPTER_INTERNAL_SERVER_ERROR";
    case Error_ErrorCode.HELLO_SIGN_ADAPTER_STALE_DATA:
      return "HELLO_SIGN_ADAPTER_STALE_DATA";
    case Error_ErrorCode.HELLO_SIGN_ADAPTER_DATA_NOT_FOUND:
      return "HELLO_SIGN_ADAPTER_DATA_NOT_FOUND";
    case Error_ErrorCode.DOCU_SUM_INVALID_PARAMETER:
      return "DOCU_SUM_INVALID_PARAMETER";
    case Error_ErrorCode.DOCU_SUM_DATA_NOT_FOUND:
      return "DOCU_SUM_DATA_NOT_FOUND";
    case Error_ErrorCode.DOCU_SUM_OPERATION_NOT_ALLOWED:
      return "DOCU_SUM_OPERATION_NOT_ALLOWED";
    case Error_ErrorCode.DOCU_SUM_STALE_DATA:
      return "DOCU_SUM_STALE_DATA";
    case Error_ErrorCode.DOCU_HOG_INVALID_PARAMETER:
      return "DOCU_HOG_INVALID_PARAMETER";
    case Error_ErrorCode.DOCU_HOG_DATA_NOT_FOUND:
      return "DOCU_HOG_DATA_NOT_FOUND";
    case Error_ErrorCode.DOCU_HOG_CONFLICT_DATA:
      return "DOCU_HOG_CONFLICT_DATA";
    case Error_ErrorCode.DOCU_VAULT_INVALID_PARAMETER:
      return "DOCU_VAULT_INVALID_PARAMETER";
    case Error_ErrorCode.DOCU_VAULT_DATA_NOT_FOUND:
      return "DOCU_VAULT_DATA_NOT_FOUND";
    case Error_ErrorCode.DOCU_VAULT_CONFLICT_DATA:
      return "DOCU_VAULT_CONFLICT_DATA";
    case Error_ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseError(): Error {
  return { code: 0, message: "" };
}

export const Error = {
  encode(message: Error, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Error {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      code: isSet(object.code) ? error_ErrorCodeFromJSON(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = error_ErrorCodeToJSON(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<Error>): Error {
    return Error.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Error>): Error {
    const message = createBaseError();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
